package com.musiqq.stockscreener.domain.model

import com.musiqq.stockscreener.data.remote.dto.EquityDto

data class Equity(
    val symbol: String,
    val name: String,
    val assetType: String = "stock",
    val exchange: String? = null,
    val sector: String? = null,
    val industry: String? = null,
    val price: Double? = null,
    val changePct: Double? = null,
    val volume: Long? = null,
    val marketCap: Long? = null,
    val peTtm: Double? = null,
    val peForward: Double? = null,
    val pbRatio: Double? = null,
    val epsTtm: Double? = null,
    val dividendYield: Double? = null,
    val week52High: Double? = null,
    val week52Low: Double? = null,
    val pctFrom52h: Double? = null,
    val ma50: Double? = null,
    val ma200: Double? = null,
    val beta: Double? = null,
    val roe: Double? = null,
    val debtToEquity: Double? = null,
    val revenueGrowth: Double? = null,
    val earningsGrowth: Double? = null,
    val analystRating: String? = null,
    val targetMean: Double? = null,
    val targetUpsidePct: Double? = null,
    val analystCount: Int? = null,
    val scoreValue: Int? = null,
    val scoreQuality: Int? = null,
    val scoreMomentum: Int? = null,
    val scoreGrowth: Int? = null,
    val scoreTotal: Int? = null,
    val expenseRatio: Double? = null,
    val aum: Long? = null,
    val indexTracked: String? = null,
    val assetClass: String? = null,
    val shortPctFloat: Double? = null,
    val insiderBuy3m: Int? = null,
    val insiderLatestType: String? = null,
    val rsi14: Double? = null,
    val relativeVolume: Double? = null,
    val dataDate: String? = null,
    // full DTO reference for detail screen
    val dto: EquityDto? = null,
)

fun EquityDto.toDomain(): Equity = Equity(
    symbol = symbol,
    name = name,
    assetType = assetType ?: "stock",
    exchange = exchange,
    sector = sector,
    industry = industry,
    price = price,
    changePct = changePct,
    volume = volume,
    marketCap = marketCap,
    peTtm = peTtm,
    peForward = peForward,
    pbRatio = pbRatio,
    epsTtm = epsTtm,
    dividendYield = dividendYield,
    week52High = week52High,
    week52Low = week52Low,
    pctFrom52h = pctFrom52h,
    ma50 = ma50,
    ma200 = ma200,
    beta = beta,
    roe = roe,
    debtToEquity = debtToEquity,
    revenueGrowth = revenueGrowth,
    earningsGrowth = earningsGrowth,
    analystRating = analystRating,
    targetMean = targetMean,
    targetUpsidePct = targetUpsidePct,
    analystCount = analystCount,
    scoreValue = scoreValue,
    scoreQuality = scoreQuality,
    scoreMomentum = scoreMomentum,
    scoreGrowth = scoreGrowth,
    scoreTotal = scoreTotal,
    expenseRatio = expenseRatio,
    aum = aum,
    indexTracked = indexTracked,
    assetClass = assetClass,
    shortPctFloat = shortPctFloat,
    insiderBuy3m = insiderBuy3m,
    insiderLatestType = insiderLatestType,
    rsi14 = rsi14,
    relativeVolume = relativeVolume,
    dataDate = dataDate,
    dto = this,
)
