package com.musiqq.stockscreener.domain.model

data class PresetSignal(
    val id: String,
    val label: String,
    val filters: Map<String, String>,
    val orderBy: String = "market_cap",
    val orderDesc: Boolean = true,
)

val PRESET_SIGNALS = listOf(
    PresetSignal("volume_surge", "거래량급등",
        mapOf("relative_volume" to "gte.2"), "relative_volume"),
    PresetSignal("new_high", "신고가",
        mapOf("pct_from_52h" to "gte.-1"), "pct_from_52h", false),
    PresetSignal("new_low", "신저가",
        mapOf("pct_from_52l" to "lte.1"), "pct_from_52l"),
    PresetSignal("high_div_value", "고배당가치주",
        mapOf("dividend_yield" to "gte.0.03", "pe_ttm" to "lte.20"), "dividend_yield"),
    PresetSignal("strong_buy", "StrongBuy",
        mapOf("analyst_rating" to "in.(strong_buy,buy)", "analyst_count" to "gte.10"), "analyst_rating_score"),
    PresetSignal("target_gap", "목표괴리20%+",
        mapOf("target_upside_pct" to "gte.20"), "target_upside_pct"),
    PresetSignal("short_squeeze", "공매도급증",
        mapOf("short_pct_float" to "gte.0.10"), "short_pct_float"),
    PresetSignal("insider_buy", "내부자매수",
        mapOf("insider_buy_3m" to "gte.3", "insider_latest_type" to "eq.Buy"), "insider_buy_3m"),
    PresetSignal("low_pe_growth", "저PER성장",
        mapOf("pe_ttm" to "lte.15", "revenue_growth" to "gte.0.15"), "revenue_growth"),
    PresetSignal("high_roe", "고ROE우량",
        mapOf("roe" to "gte.0.20", "debt_to_equity" to "lte.100"), "roe"),
    PresetSignal("oversold", "과매도",
        mapOf("rsi_14" to "lte.30"), "rsi_14"),
    PresetSignal("overbought", "과매수",
        mapOf("rsi_14" to "gte.70"), "rsi_14", false),
    PresetSignal("top_gainer", "오늘급등",
        mapOf("change_pct" to "gte.5"), "change_pct"),
    PresetSignal("top_loser", "오늘급락",
        mapOf("change_pct" to "lte.-5"), "change_pct", false),
    PresetSignal("score_80", "종합80+",
        mapOf("score_total" to "gte.80"), "score_total"),
    PresetSignal("dcf_undervalued", "DCF저평가",
        mapOf("dcf_upside_pct" to "gte.20"), "dcf_upside_pct"),
    PresetSignal("momentum", "모멘텀폭발",
        mapOf("score_momentum" to "gte.90", "relative_volume" to "gte.1.5"), "score_momentum"),
    PresetSignal("quality_value", "퀄리티+밸류",
        mapOf("score_quality" to "gte.80", "score_value" to "gte.80"), "score_total"),
    PresetSignal("shareholder", "주주환원5%+",
        mapOf("shareholder_yield" to "gte.0.05"), "shareholder_yield"),
    PresetSignal("perf_1y", "1년수익50%+",
        mapOf("perf_1y" to "gte.0.50"), "perf_1y"),
)
